; Opening book probe (shared by C64 and headless/test builds).
;
; The book data itself lives in opening_book_data.s (auto-generated by
; tools/compile_opening_book.py): a 16-bit BookEntryCount followed by
; BookHashTable, a flat array of 4-byte records sorted ascending by the
; engine's own 16-bit Zobrist key:
;
;   +0  key_lo
;   +1  key_hi
;   +2  from   (0x88 square byte, as MoveListFrom)
;   +3  to     (0x88 square byte, as MoveListTo)
;
; The key is whatever ComputeZobristHash produced for the position (it is NOT
; reimplemented anywhere -- the compiler drives the engine to get it). Because
; the key is only 16 bits, collisions are possible; the search hook re-validates
; any returned move against GenerateLegalMoves, so a colliding key that yields an
; illegal move degrades to "miss, search normally" (see search.s FindBestMove).

.segment "CODE"

;
; LookupOpeningMove
; Input:  ZobristHash / ZobristHash+1 = current position key (set by the caller
;         via ComputeZobristHash).
; Output: Carry SET  -> book hit, A = from square, Y = to square.
;         Carry CLEAR -> miss (not in book).
; Clobbers: A, X, Y, $fb, $fc, BookLo/BookHi/BookMid.
;
; Binary search over BookHashTable[0 .. BookEntryCount-1].
;
LookupOpeningMove:
; BookLo = 0
  lda #$00
  sta BookLo
  sta BookLo + 1
; BookHi = BookEntryCount (exclusive upper bound)
  lda BookEntryCount
  sta BookHi
  lda BookEntryCount + 1
  sta BookHi + 1

__ai_book_loop_0:
; while (BookLo < BookHi)  -- 16-bit unsigned compare, hi byte first
  lda BookLo + 1
  cmp BookHi + 1
  bcc __ai_book_in_range_0; LoHi < HiHi -> Lo < Hi
  bne __ai_book_done_0; LoHi > HiHi -> Lo >= Hi -> done
  lda BookLo
  cmp BookHi
  bcc __ai_book_in_range_0; LoLo < HiLo -> Lo < Hi
__ai_book_done_0:
  jmp __ai_book_miss_0; Lo >= Hi -> done

__ai_book_in_range_0:
; BookMid = (BookLo + BookHi) >> 1   (counts are small, no 17th-bit overflow)
  clc
  lda BookLo
  adc BookHi
  sta BookMid
  lda BookLo + 1
  adc BookHi + 1
  sta BookMid + 1
  lsr BookMid + 1
  ror BookMid

; $fb/$fc = BookHashTable + BookMid * 4   (4 bytes per entry)
  lda BookMid
  asl
  sta $fb
  lda BookMid + 1
  rol
  sta $fc
  asl $fb
  rol $fc
  clc
  lda $fb
  adc #<BookHashTable
  sta $fb
  lda $fc
  adc #>BookHashTable
  sta $fc

; Compare entry key vs target (hi byte first)
  ldy #$01
  lda ($fb), y; entry key_hi
  cmp ZobristHash + 1
  bcc __ai_book_entry_less_0; entryHi < targetHi -> entry < target
  bne __ai_book_entry_greater_0; entryHi > targetHi -> entry > target
  dey
  lda ($fb), y; entry key_lo
  cmp ZobristHash
  bcc __ai_book_entry_less_0
  bne __ai_book_entry_greater_0

; Equal -> hit. Load from -> A, to -> Y.
  ldy #$02
  lda ($fb), y; from
  pha
  iny
  lda ($fb), y; to
  tay
  pla
  sec
  rts

__ai_book_entry_less_0:
; BookLo = BookMid + 1
  clc
  lda BookMid
  adc #$01
  sta BookLo
  lda BookMid + 1
  adc #$00
  sta BookLo + 1
  jmp __ai_book_loop_0

__ai_book_entry_greater_0:
; BookHi = BookMid
  lda BookMid
  sta BookHi
  lda BookMid + 1
  sta BookHi + 1
  jmp __ai_book_loop_0

__ai_book_miss_0:
  clc
  rts

.segment "BSS"

BookLo:
  .res 2
BookHi:
  .res 2
BookMid:
  .res 2

.segment "CODE"
