#!/usr/bin/env python3
"""Compile tools/opening_repertoire.json into the engine's linked opening book.

This is the OFFLINE producer for src/ai/opening_book_data.s. For every repertoire
entry it:

  1. builds the C64 board state from the FEN,
  2. asks the *engine itself* (via the sim6502 bridge `zobrist` command) for the
     16-bit Zobrist key -- the hash is never reimplemented in Python, so the key
     is bug-for-bug identical to what the engine computes while playing,
  3. converts ``best_move_uci`` to the engine's from/to 0x88 square bytes (the
     same encoding GenerateLegalMoves produces in MoveListFrom/MoveListTo),
  4. de-duplicates on the engine key (16-bit -> collisions possible; keep the
     lower-ply / mainline entry),
  5. sorts ascending by key and emits a flat 4-byte-per-record table for the
     6502 binary search in src/ai/opening_book.s.

Run it against a known-good engine build when the tree is quiet:

    make engine-build
    python3 tools/compile_opening_book.py
    make engine-build   # relink with the populated book

Every runtime failure path (miss, key collision, hung-piece guard) degrades to a
normal search, so a stale or empty book is never a correctness problem.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import chess  # noqa: E402

from run_stockfish_strength import fen_to_c64, square_to_0x88  # noqa: E402
from sim6502_headless_runner import Sim6502HeadlessRunner, repo_root_from_script  # noqa: E402

# Mirror of the reserved ceiling in src/constants.s (BOOK_HASH_SIZE = $4A00).
# 4 bytes/record -> ~4,736 records. The data is now a linked segment rather than
# loaded into the fixed $5600 region, but we keep the same ceiling so an
# accidental blob explosion fails the compile loudly instead of bloating RAM.
BOOK_HASH_SIZE = 0x4A00
BYTES_PER_ENTRY = 4
MAX_ENTRIES = BOOK_HASH_SIZE // BYTES_PER_ENTRY


def uci_to_engine_squares(uci: str) -> tuple[int, int]:
    """Return (from, to) engine 0x88 square bytes for a UCI move.

    Castling is king e1g1/e1c1/e8g8/e8c8 -- identical to how GenerateCastlingMoves
    encodes it. Bit 7 of `to` is the knight-promotion flag (queen promo and all
    normal moves leave it clear); opening lines never promote, but handle it
    anyway so the legality compare in the search hook matches MoveListTo exactly.
    """
    move = chess.Move.from_uci(uci)
    frm = square_to_0x88(move.from_square)
    to = square_to_0x88(move.to_square)
    if move.promotion == chess.KNIGHT:
        to |= 0x80
    if frm & 0x88 or (to & 0x7F) & 0x88:
        raise ValueError(f"move {uci} produced off-board squares: from={frm:#x} to={to:#x}")
    return frm, to


def compile_entries(repo_root: Path, repertoire: dict) -> tuple[list[dict], int]:
    entries = repertoire["entries"]
    by_key: dict[int, dict] = {}
    collisions = 0

    with Sim6502HeadlessRunner(repo_root=repo_root) as runner:
        for raw in entries:
            fen = raw["fen"]
            uci = raw["best_move_uci"]
            ply = int(raw.get("ply", 0))
            c64 = fen_to_c64(fen)
            response = runner.zobrist(c64)
            key = int(response["key"]) & 0xFFFF
            frm, to = uci_to_engine_squares(uci)

            record = {
                "key": key,
                "from": frm,
                "to": to,
                "ply": ply,
                "uci": uci,
                "san": raw.get("best_move_san", ""),
                "line": raw.get("line_name", ""),
                "fen": fen,
            }

            existing = by_key.get(key)
            if existing is None:
                by_key[key] = record
                continue

            collisions += 1
            # Keep the lower-ply (mainline) entry on a 16-bit key clash.
            if ply < existing["ply"]:
                by_key[key] = record

    ordered = sorted(by_key.values(), key=lambda r: r["key"])
    return ordered, collisions


def render_book_asm(records: list[dict], collisions: int, source_rel: str) -> str:
    lines: list[str] = []
    lines.append("; AUTO-GENERATED by tools/compile_opening_book.py -- DO NOT EDIT BY HAND.")
    lines.append(";")
    lines.append("; Opening book: BookEntryCount (16-bit) + BookHashTable, a flat array of 4-byte")
    lines.append("; records (key_lo, key_hi, from, to) sorted ascending by the engine's own 16-bit")
    lines.append("; Zobrist key. Keys come straight from ComputeZobristHash via the sim6502 bridge,")
    lines.append("; so they match what the engine plays with. The 6502 binary search lives in")
    lines.append("; src/ai/opening_book.s; the search hook re-validates every hit against legal")
    lines.append("; moves, so a 16-bit collision can never produce an illegal move.")
    lines.append(";")
    lines.append(f"; source : {source_rel}")
    lines.append(f"; entries: {len(records)}")
    lines.append(f"; key collisions dropped: {collisions}")
    lines.append("")
    lines.append('.segment "RODATA"')
    lines.append("")
    lines.append("BookEntryCount:")
    lines.append(f"  .word {len(records)}")
    lines.append("")
    lines.append("BookHashTable:")
    for r in records:
        key = r["key"]
        comment = f"key=${key:04X} {r['uci']}"
        if r["san"]:
            comment += f" ({r['san']})"
        if r["line"]:
            comment += f" {r['line']}"
        lines.append(
            f"  .byte ${key & 0xFF:02X},${(key >> 8) & 0xFF:02X},"
            f"${r['from'] & 0xFF:02X},${r['to'] & 0xFF:02X}  ; {comment}"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    repo_root = repo_root_from_script()
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repo-root", type=Path, default=repo_root)
    parser.add_argument("--input", type=Path, default=repo_root / "tools" / "opening_repertoire.json")
    parser.add_argument("--output", type=Path, default=repo_root / "src" / "ai" / "opening_book_data.s")
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    repertoire = json.loads(args.input.read_text())
    records, collisions = compile_entries(repo_root, repertoire)

    if len(records) > MAX_ENTRIES:
        raise SystemExit(
            f"Opening book overflow: {len(records)} entries > {MAX_ENTRIES} "
            f"({len(records) * BYTES_PER_ENTRY} bytes > BOOK_HASH_SIZE {BOOK_HASH_SIZE})."
        )

    source_rel = str(args.input.relative_to(repo_root)) if args.input.is_relative_to(repo_root) else str(args.input)
    asm = render_book_asm(records, collisions, source_rel)
    args.output.write_text(asm)

    print(
        f"Wrote {args.output} : {len(records)} entries "
        f"({len(records) * BYTES_PER_ENTRY} bytes), {collisions} key collisions dropped."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
