/* egtb.h -- Phase-1 (3-man) endgame tablebase probe.
 *
 * On a position with <= 3 men whose material is KQK/KRK/KPK, egtb_probe returns the
 * EXACT game-theoretic value (from the side-to-move) as a search score, derived from
 * the DTM byte tables generated by tools/egtb_gen.py. The index function here MUST be
 * byte-identical to that generator (verified by test/egtb_parity).
 *
 * Storage: the packed table blob (build/egtb_tables.bin) lives off-chip in the REU on
 * the C64 (CREF_TT_REU) -- read one byte per probe via $DF00 DMA -- or in a flat host
 * buffer for validation. Call egtb_set_data() on host before probing. */
#ifndef CREF_EGTB_H
#define CREF_EGTB_H

#include "board.h"

/* Probe. Returns 1 and sets *score (side-to-move POV: +mate / 0 draw / -mate) when the
 * position is a covered 3-man table entry; returns 0 (no table) otherwise. `ply` is the
 * node's search ply (mate scores are anchored to it). */
int egtb_probe(const Board *b, int ply, int *score);

/* Host/validation only: point the probe at a flat in-RAM copy of egtb_tables.bin. */
void egtb_set_data(const unsigned char *blob);

#endif
